//
//  DummyComics.swift
//  ComicReader
//
//  Created by Ade Hendra on 20/07/21.
//  Copyright © 2021 Organisasi Berbudaya. All rights reserved.
//

import Foundation
import UIKit

var comics : [Comic] =
[
    Comic(photo : UIImage(named: "demonslayer")!,title: "Blade of Demon Destruction", description: "Tanjiro is the oldest son in his family who has lost his father. One day, Tanjiro ventures off to another town to sell charcoal. Instead of going home, he ends up staying the night at someone else's house due to rumors of a demon nearby in the mountains. When he gets home the following day, a terrible tragedy awaits him."),
    Comic(photo: UIImage(named: "sololeveling")!, title: "Solo Leveling", description: "10 years ago, after the Gate that connected the real world with the monster world opened, some of the ordinary, everyday people received the power to hunt monsters within the Gate. They are known as Hunters. However, not all Hunters are powerful. My name is Sung Jin-Woo, an E-rank Hunter. I'm someone who has to risk his life in the lowliest of dungeons, the World's Weakest. Having no skills whatsoever to display, I barely earned the required money by fighting in low-leveled dungeons… at least until I found a hidden dungeon with the hardest difficulty within the D-rank dungeons! In the end, as I was accepting death, I suddenly received a strange power, a quest log that only I could see, a secret to leveling up that only I know about! If I trained in accordance with my quests and hunted monsters, my level would rise. Changing from the weakest Hunter to the strongest S-rank Hunter!"),
    Comic(photo: UIImage(named: "onepiece")!, title: "One Piece", description: "Follows the adventurous and funny story of Monkey D. Luffy. As a boy, Luffy has always wanted to be the Pirate King. His body obtained the properties of rubber after eating a Devil Fruit. Together with a diverse crew of wannabe pirates, Luffy sets out on the ocean in an attempt to find the world’s ultimate treasure, One Piece.When talking about the most successful manga and anime series of all time, One Piece will always enter the conversation. Just the mere fact of it running for almost decades goes to show how loved it is by millions of fans worldwide."),
    Comic(photo: UIImage(named: "slime")!, title: "Regarding My Reincarnation as a Slime", description: "A man is stabbed by a robber on the run after pushing his coworker and his coworker's new fiance out of the way. As he lays dying, bleeding on the ground, he hears a voice. This voice is strange and interprets his dying regret of being a virgin by gives him the [Great Sage] unique skill! Is he being made fun of !?!"),
    Comic(photo: UIImage(named: "tog")!, title: "Tower of God", description: "The storyline centers around a boy called Twenty-Fifth Baam, that has spent his life trapped beneath a tower that was mysterious. Chasing after his only friend, as he attempts to locate his company, he manages to open a door to the Tower, and must face challenges at every floor of the cryptic tower.The Tower is a cryptic construction which is totally enclosed and hosts many surroundings that are exceptional."),
    Comic(photo: UIImage(named: "blackclover")!, title: "Black Clover", description: "Aster and Yuno were abandoned together at the same church, and have been inseparable since. As children, they promised that they would compete against each other to see who would become the next sorcerous emperor. However, as they grew up, some differences between them became plain. Yuno was a genius with magic, with amazing power and control, while Aster could not use magic at all, and tried to make up for his lack by training physically. When they received their grimoires at age 15, Yuno got a spectacular book with a four-leaf-clover (most people receive a three-leaf-clover), while Aster received nothing at all. However, when Yuno was threatened, the truth about Aster's power was revealed-- he received a five-leaf-clover grimoire, a 'black clover' book of anti-magic."),
    Comic(photo: UIImage(named: "attackontitan")!, title: "Attack on Titan", description: "Eren Jaeger, a ten-year-old boy who had witnessed his own mother perish in the hands of the titans, vowed to avenge his mother’s death against the titans and wipe the giant creatures out completely. The boy joined Training Corps, which trained people who were ready to join the war against titans, and five years later he fights his first battle against the titans.The narrative of Attack on Titan Manga revolves around the experiences of his foster sister, Eren Yeager, Mikasa Ackerman, Armin Arlert, as well as their childhood friend."),
    Comic(photo: UIImage(named: "shieldhero")!, title: "The Rising of The Shield Hero", description: "Naofumi Iwatani, an uncharismatic Otaku who spends his days on games and manga, suddenly finds himself summoned to a parallel universe! He discovers he is one of four heroes equipped with legendary weapons and tasked with saving the world from its prophesied destruction. As the Shield Hero, the weakest of the heroes, all is not as it seems. Naofumi is soon alone, penniless, and betrayed. With no one to turn to, and nowhere to run, he is left with only his shield. Now, Naofumi must rise to become the legendary Shield Hero and save the world!"),
    Comic(photo: UIImage(named: "nanatsu")!, title: "The Seven Deadly Sins", description: "The Dragon's the captain of the Seven Deadly Sins as well as Sin of Wrath. He could be the primary protagonist and owner of the Boar Hat Pub, known because of its incredible ale and less understood because of its terrible food (cooked by Meliodas). Although he seems to be no older than the usual kid, Meliodas is significantly older than he seems and is really quite strong. Despite being the Sin of Wrath, he's seldom upset, and is, actually, perverted childishly lively, assured, demonic, and kind to those he cares about."),
    Comic(photo: UIImage(named: "bleach")!, title: "Bleach", description: "Ichigo Kurosaki is an ordinary high schooler—until his family is attacked by a Hollow, a corrupt spirit that seeks to devour human souls. It is then that he meets a Soul Reaper named Rukia Kuchiki, who gets injured while protecting Ichigo's family from the assailant. To save his family, Ichigo accepts Rukia's offer of taking her powers and becomes a Soul Reaper as a result.owever, as Rukia is unable to regain her powers, Ichigo is given the daunting task of hunting down the Hollows that plague their town. However, he is not alone in his fight, as he is later joined by his friends—classmates Orihime Inoue, Yasutora Sado, and Uryuu Ishida—who each have their own unique abilities. As Ichigo and his comrades get used to their new duties and support each other on and off the battlefield, the young Soul Reaper soon learns that the Hollows are not the only real threat to the human world.")
]
